// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiKPC5kr9SxxIfPNd0pQYMmTROZat9Apk',
    appId: '1:696309210058:web:a5accac134499a5636cd33',
    messagingSenderId: '696309210058',
    projectId: 'music-2ac9e',
    authDomain: 'music-2ac9e.firebaseapp.com',
    storageBucket: 'music-2ac9e.appspot.com',
    measurementId: 'G-VRMVSBTG7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5-hvBbgQ2uc0CRojquYKnND0g6v0NMUc',
    appId: '1:696309210058:android:6cfbf048f987e0bd36cd33',
    messagingSenderId: '696309210058',
    projectId: 'music-2ac9e',
    storageBucket: 'music-2ac9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj4R1wO5Zl0AiWeGR67Ig9jws5aR0281I',
    appId: '1:696309210058:ios:05c78bafd706cf4d36cd33',
    messagingSenderId: '696309210058',
    projectId: 'music-2ac9e',
    storageBucket: 'music-2ac9e.appspot.com',
    iosBundleId: 'com.example.cloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj4R1wO5Zl0AiWeGR67Ig9jws5aR0281I',
    appId: '1:696309210058:ios:05c78bafd706cf4d36cd33',
    messagingSenderId: '696309210058',
    projectId: 'music-2ac9e',
    storageBucket: 'music-2ac9e.appspot.com',
    iosBundleId: 'com.example.cloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiKPC5kr9SxxIfPNd0pQYMmTROZat9Apk',
    appId: '1:696309210058:web:4eb379410c079a7f36cd33',
    messagingSenderId: '696309210058',
    projectId: 'music-2ac9e',
    authDomain: 'music-2ac9e.firebaseapp.com',
    storageBucket: 'music-2ac9e.appspot.com',
    measurementId: 'G-LS4YT2V6JR',
  );
}
